service: merge-lock-github-service

provider:
  profile: release-bot
  name: aws
  runtime: python2.7
  stage: dev
  region: eu-west-1
  iamRoleStatements:
    - Effect: "Allow"
      Resource: "*"
      Action:
        - "sns:*"

package:
  include:
    - ../commons/**

custom:
  writeEnvVars:
    STAGE: ${opt:stage}
    REGION: ${opt:region}
    DEV_USER_SERVICE_API_ID: ${file(../env_vars.yml):DEV_USER_SERVICE_API_ID}

    PROD_USER_SERVICE_API_ID: ${file(../env_vars.yml):PROD_USER_SERVICE_API_ID}

    ACCOUNT_ID: ${file(../env_vars.yml):ACCOUNT_ID}
    
plugins:
  - serverless-plugin-write-env-vars


functions:
  functionPush:
    handler: handler.push
    events:
      - http:
          path: github/push
          method: post

resources:
  Resources:
    pushTopic:
      Type: "AWS::SNS::Topic"
      Properties:
        TopicName: ${opt:stage}-push
